---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1u9qu2c4mc3pcave6smwyv960vq4tjnrdq76k8aq7n6xnl9p6kpns08jkst
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1u9qu2c4mc3pcave6smwyv960vq4tjnrdq76k8aq7n6xnl9p6kpns08jkst
