---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: highseas-downloads
  namespace: highseas
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Gi
