# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nfs-secrets
    namespace: storage
stringData:
    SECRET_NFS_SERVER_IP: ENC[AES256_GCM,data:j2RdHWKFzyvO,iv:LYfzO1ioqp5TiBA0rMPStUNnETKwbQJULgZxLIaqJIo=,tag:o0GxD8Hy6RQ6jZvXkyTG4w==,type:str]
    SECRET_NFS_SERVER_MEDIA_PATH: ENC[AES256_GCM,data:k5I4/iwX1uce8+dByfTGGxI=,iv:vsH/SvTZFC5ujWuiEpzQUgkmbxCuEqBImEqnORmd8Ao=,tag:C7kPkGIqXvyOfWmty8KzoA==,type:str]
    SECRET_NFS_SERVER_ARCHIVE_PATH: ENC[AES256_GCM,data:1nbh7TbJmFsbAizeSTPXRA45BShjug==,iv:/eA+zwwvTfrU4ew5NdA2k4uQMGRbrQ9UUGC+z84wnjc=,tag:vmPfY5bUUPX5YJtJA6URkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bXF1cjdxR0ZNUUp5MjBL
            bWhEOXJtVUttVWpYRGY3eml0eFlEV2tZb2dVCitoY3gwd1NhL3JwRk9BVGdTWVY2
            cmx4dVJ6SnVXM3dsaXJ0Rkt2d2lOYTgKLS0tIHlzM09lRENrT0NlUUIxaXhFbUZ4
            YkZDR1czRSt3M3VOL1RYMm9lUDZYRUEKBUiuh0CHO1iizF1r37E2QRwKwmBfcpho
            xf7r/6idaUPeHCH0Y4+qdQdV60TxeRPl5MCLJA1HKsOBeJwHRY2REw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-13T19:11:25Z"
    mac: ENC[AES256_GCM,data:YB00TPeuBEulKnhsHibIWMcSuv4OpoWsm6Kt+pBjs94zxCxxY4MrSHIk7Noj/b6Sp0spfnqQ61b7t356Y841ZvDZWY21PI0C8tNilaXG7nKsqcTF8z+HZgivxe8HU3jsdPBvr2xHh/m8rRD0wG9+qaNcS1DPtf6UE2OwGAI1EwM=,iv:970pE3RrffaG7UtRbbNKnsTVr10BG4pLVSO8hSZjKH4=,tag:sLaDRuZnKqo2QmUDnSrOAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
