---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-v2
  namespace: lowseas
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
