---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: lowseas
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true

  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr-develop
      tag: v3.0.9.1555

    env:
      TZ: '${TIMEZONE}'

    service:
      main:
        ports:
          http:
            port: 8989

    ingress:
      main:
        enabled: true
        ingressClassName: 'nginx'
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'cloud-download'
          nginx.ingress.kubernetes.io/whitelist-source-range: "${SECRET_NETWORK_INGRESS_WHITELIST}"
        hosts:
          - host: 'sonarr.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'sonarr.${SECRET_DOMAIN}'
            secretName: 'sonarr-tls'

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        type: nfs
        server: "${SECRET_NFS_SERVER_IP}"
        path: "${SECRET_NFS_SERVER_MEDIA_PATH}"
        mountPath: /media

    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
