# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: pihole-secrets
    namespace: networking
stringData:
    SECRET_PIHOLE_ADMIN_PASS: ENC[AES256_GCM,data:7goK7fDX+lBTF16ilrY5oeTzIZc=,iv:hp1D8udI8S4ZF5yUnDWRClu7EUmAcH4AmZ3YMOpVShg=,tag:LuDQNbYyJBfclCps+cZ9ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRFpVa2x2Wk90cHRoQmZR
            aDdVT0ZZaUdsNUFqeWQ3UmFpRENXWDJPQ3dvCkhVZGM4ZVREYmVHbCt6YzQxdWJv
            czdQSWhTaXdYVkxUN3V0bGNWYm8xQmcKLS0tIFZHNHR3VW5tbjV4TGdxNjAvd1Q4
            cFdPTTFSTWtYck11UktrY21MK012VFEKPmhFNJ7cf6E2XIsTd84CYu/5nEXDH3Gb
            RCpD3/998ppRZQiGFBcZL60tPlbRTHbi90hCr1zpcvN47q1BFuMYjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-13T19:10:47Z"
    mac: ENC[AES256_GCM,data:Kzfq1f08uT9dIQ/zHHeevgBWIblaavNDTk1aGyG7T7+IgfH9sTJTst2x/FjDmTtaQe0eg1IaifasaIGXohYeS8sSKCI/oipTKp0hK3onEz56jbiaJ1KdVcCWp0HwxJVWDCJcL6XjIAxov3sC/w5EvgX7tPzc4LAAS0OHWnwxaB0=,iv:zS1u/ia7r1sYNN87ZG8r3UlDhjByStRRPFzrT0VZT2M=,tag:RYV7FoJv0rjlPMQDqO/d4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
