# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: lowseas-secrets
    namespace: lowseas
stringData:
    SECRET_NFS_SERVER_IP: ENC[AES256_GCM,data:tPyxryqyh6ce,iv:NFdV7WYo4H+nPtq8q7TGMxdPYPcEizPHyPWBmJno7y8=,tag:o0AKOgsGgzJLUGlkSJ0f+Q==,type:str]
    SECRET_NFS_SERVER_MEDIA_PATH: ENC[AES256_GCM,data:8v+MTzSJ8Js1TYPPEqx7uh0=,iv:CoE4Vt7h93SiHP7IgqxR/BpNX8V15nt5MALGdMvt5Tk=,tag:WCq8jjjemvpqrgN6i6MClQ==,type:str]
    SECRET_SERVICE_USER: ENC[AES256_GCM,data:fWpjDw==,iv:XBD24fKVBWEfUOsooJfq0HjTjVqLem3D/2QJ9VcBjmg=,tag:Wabtc3oL5qK6d2oRiJAvDQ==,type:str]
    SECRET_SERVICE_PASS: ENC[AES256_GCM,data:iKTCavY1Bw5EgaFaRZZiR5Q=,iv:r55DdGSZhTWdDcjynrNMpaDXWaAhB8qEWCffdc9CerI=,tag:/YZX3tx3ai7N9AJ8Llke+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXY2dub2RYTkQwd2ZKR0dR
            MXBGUituYW5CN0swdVlEdllrdHdNaGl2NG13Ckg5S091SlArckk1MzJnS2R0L3Qv
            d1NtVDkxcjEvZ2E4Wm5raXhUU3ZIK00KLS0tIGV5K21mK2FMOTVCaTBDdnRKdmE0
            YkVKdUt1SnNYNVkzdDh1WUl2YnVrU3cKRFWAC1Zw++f0H9ZFX9FH7CSJZFB0OL7X
            Lk6LTKvgDI11ulpd7ZkCEJWOES/iKDfXJjWds8PrmO/lJVnPZrloeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-13T19:35:59Z"
    mac: ENC[AES256_GCM,data:hlPxQHr/cPz8T6gnLgMmqtzWjW4o8TBSrW6QCDODyWQtZEPhg4Y7wg3r18y0nZAVr3q3/72/VGT4mZBHQYyHh3HxyXb6QNzlWPgU5ig5Us0fK8n86Dpjwy035u5UY2BE4EI4/+JfYQlsMz5ZMKZuxBKBAK6ZsXcqZFHkmHL1GZQ=,iv:E3fbwU1cA4zUxfYPHArDOBFZuH6VIlEid3FHZr/B67M=,tag:rc8ENgrR9Zuo9qIOGMf3vA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
