# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: lowseas-secrets
    namespace: lowseas
stringData:
    SECRET_NFS_SERVER_IP: ENC[AES256_GCM,data:2vKT1kVpHaK4,iv:ZzMUmO0xWKxb2ABvnPXq6rDATKUEpAhDLCNEQfGUjsY=,tag:KRMzJ7rJErqTOpw7OJiyLg==,type:str]
    SECRET_NFS_SERVER_MEDIA_PATH: ENC[AES256_GCM,data:YWRqWyOGLboRTobyg3oi7Bo=,iv:uRr1AOGaIksWBugGlvl9Y/K3NYW7Lxvma9h0Rd1dEh4=,tag:IUEpl8T3E93U3ii2CmEg6A==,type:str]
    SECRET_SERVICE_USER: ENC[AES256_GCM,data:20oKUg==,iv:Tv2zFFwjVfTACqf/RLn090ugMp00yI1KLzy4sPg94Mo=,tag:sPmYUtL8oAA4Vqehpj4Vig==,type:str]
    SECRET_SERVICE_PASS: ENC[AES256_GCM,data:R95YlBK5MyQNR6O9rcP+ev8=,iv:WcqT0WzDnmEjbooz4yLPL9zEn0d4IipfRMzmGTXtaIQ=,tag:VVJF8W3meR2lMsi+2u5Baw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYlJDOVZsREpKTDJmWUFX
            VzAzUDgvNmFSN292Y0RBV1pFb0lyb09rbVdRCjNGQlR4WnlhOVlua2psVzVjbEUr
            dWhyNXpEa2lVcWZEMEkxajdaNXM2VTAKLS0tIHkwVndBZ3pxMDNzdmJDa2o3UmFm
            cnpqR25xR1ZKYldwSjFqSG5SeDBZNTQKV5PrJwE/d1zmsH0U/jpXi8i+kz7atgnQ
            5dpD4gqmgAe0PnDp1MOtd98ZZOdkmb6SXZWdBnM9NNwbuUk5V4dzcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-13T19:11:46Z"
    mac: ENC[AES256_GCM,data:p8xDEuuqx7ddTnj+E9/xmHC2I0xh0mI55lnNVo3yxmC80MvfbvpPuuoUphBvIDPPHzhE6eKTzRzuOam8ijjclstYJ7HCVkoNoFGGtdaUW2zagTcbfWeAlIf6wsqmRO/ewqetum3NVW8SAnFSuQgHzQHEEgRAVjin2GrOiLXGvtw=,iv:wMEkWBDuwJ8DwszjLORMd3UHf//h8pB0faCUOen+RdU=,tag:ickjX6I8mm+xyNQ9ikGzWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
