---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config-v2
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
