---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: vaultwarden/server
      tag: 1.25.0
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
    env:
      SIGNUPS_ALLOWED: false
      INVITATIONS_ALLOWED: true
      WEBSOCKET_ENABLED: true
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_PORT: 3012
      DOMAIN: https://vault.${SECRET_DOMAIN}
      ADMIN_TOKEN: ${SECRET_VAULTWARDEN_ADMIN_TOKEN}
      SMTP_HOST: "${SECRET_VAULTWARDEN_EMAIL_HOST}"
      SMTP_FROM: "${SECRET_VAULTWARDEN_EMAIL_ADDR}"
      SMTP_FROM_NAME: "${SECRET_VAULTWARDEN_EMAIL_FROM}"
      SMTP_SECURITY: starttls
      SMTP_PORT: 587
      SMTP_USERNAME: "${SECRET_VAULTWARDEN_EMAIL_USER}"
      SMTP_PASSWORD: "${SECRET_VAULTWARDEN_EMAIL_KEY}"
      YUBICO_CLIENT_ID: "${SECRET_VAULTWARDEN_YUBICO_CLIENT_ID}"
      YUBICO_SECRET_KEY: "${SECRET_VAULTWARDEN_YUBICO_SECRET_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-key"
          hajimari.io/appName: "vaultwarden"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: "vault.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
              - path: /notifications/hub/negotiate
                pathType: Prefix
        tls:
          - hosts:
              - "vault.${SECRET_DOMAIN}"
            secretName: "vaultwarden-tls"
    resources:
      requests:
        memory: 500Mi
        cpu: 200m
      limits:
        memory: 2000Mi
