---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpn-gateway-config
  namespace: networking
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
