---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Make sure /mnt/MEDIA exists
      ansible.builtin.file:
        path: /mnt/MEDIA
        state: directory

    - name: Mount /mnt/ACKHAX/MEDIA
      ansible.posix.mount:
        path: /mnt/MEDIA
        src: "10.0.0.40:/mnt/ACKHAX/MEDIA"
        fstype: nfs
        opts: soft,intr,rsize=8192,wsize=8192,sec=sys,vers=4
        state: mounted
