# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres14-secrets
    namespace: dbs
stringData:
    postgres-password: ENC[AES256_GCM,data:MrBKjYAXYJsUZopzhlo2R/KsfxR/EZF7KRGC9XqAjzs=,iv:PacbkJZLjJIL3vvWtMQ+GCNTJUNpFpZ0A0DH87gZ0Is=,tag:1/1S4ld9sTmEsRyT4/Rnvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR1A5YkdPVUxUMHlrdVFW
            VytpWk1vcnBWN1ZoaTBxYmRJUUIrRUhreVRNClI3QzJ4a1p4dTFwMjlOSXdtaCtj
            b1R4YSsxMnBpbFMrQmU1N0V2YWNyUjgKLS0tIEpQSkthS1kxMWpqdVJSSk9jSEl2
            MGRRbERQUENoVmR5dWhrYUR5ZEs5eUEKxVJ5pGgjlRQobxV+g1cccS4DR9Q0W5c9
            xpvkQUTQ1sAd5bLiWJ3ABiMcOoRdHnF0DQ900jM/+jmxXPMsAAWnTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-05T00:09:10Z"
    mac: ENC[AES256_GCM,data:rcovi1E4zqkulcOSjPoVuVrW/Qx/RNWXYKvkl66B1ZyHN8A1XpigdD1kgwMYwQwHjA5jihV4FxgV7CAUu/pxlWDchNy9315zKaUdPBoG8rRIJUqsbT7XlhjzVMnT+V1XZIvrBKITN4mpFVGUXasrAvWubmfSdRgMv3LdhK1HupU=,iv:fvlDl3GE6jgy+WX6F1Zlo1bQAC8HImTczzNYoWnN2L0=,tag:8aPWGGzIg1HfF86PpJXu8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
