---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin-family
  namespace: family
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.runix.net
      chart: pgadmin4
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: runix-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      email: ${SECRET_PGADMIN_EMAIL}
      password: ${SECRET_PGADMIN_PASS}

    strategy:
      type: Recreate

    persistentVolume:
      enabled: true
      existingClaim: pgadmin-fam-config

    ingress:
      enabled: true
      hosts:
        - host: "pgadmin-fam.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "pgadmin-fam.${SECRET_DOMAIN}"
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Ingress
              name: pgadmin-pgadmin4
            patch:
              - op: add
                path: /spec/ingressClassName
                value: nginx
