# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:sM9eM/wKnF4rjb7S/W8ao3cKvd3KyyTxufDkGqfBWIPqpr38AA==,iv:B+c1AemS0vW+l0A8dbOzozruERoalYaERF261H+fTGA=,tag:WBKYG0QWbwlTAClQegN35A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNHlCbWR3VjJCTmRKbXZW
            alNJMWR3Ni9BM3Q2Rk9lK2R4bTk1dEtpUVFNClI3SmxFL0RVY1RUU1dINWc4UERX
            RXZPdUFNc0RNV1ZEVU82UThOVkRNVkEKLS0tIHVlZ3Bpa2MzZDBxWXg0Vkg1aStC
            d2VkdG9RdzdhOHpPRXlIcnI1YUFGanMK29yVJIa8iy182Halj6IxbU5ZEmmrucMw
            MiALlSIMugyYn4CXugDWq2eLo5m6hHKtdcqYk7XwAlsSNSHyCXg7NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T04:56:15Z"
    mac: ENC[AES256_GCM,data:9mjk7eLWIQ0GbnaV4LOPvyR3tgpozJIgh4rTukUYPpmyxSoNDdoc4mGg0z8abym2HkCrIqELDuDS2DReOXSgJoo9JbIFP1bsMzsAbqgy57sw1ppFQ1/G9sLyEhAHZMLMGbotQuGgDvLa7eF8k9M8n8zWBMUbn+V4flZjBvLZWco=,iv:2jUJxXeD/+08ptPIan/yDpP12fPbL0f6CuyF5yVe2Qw=,tag:+/4ofXSPoEsjABS0ePq+wA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
