# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:4pspk+JUYJig5RbJa9/+vRd+SLqxx0/Y0zvAmGigIQ4BtmSMvQ==,iv:RkpGutS4E2J2LiT+wXy1NlPnSiOmeYt+lOA5xrIbLvY=,tag:AtdDbhqp5vG2ADz73Fn4NQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZUNqakw1Q1hXQjlvVXkw
            ZjdHb2kxM1lvUm1nR1FSOXB5UVY5SzZQb0Q4CjRFVm9IRXdCMVNMWW0zMnlUYmRp
            RDVJNGRaRGFwclpqSVJCSU5EdXAzckEKLS0tIGk1aHJubjAxOTFram1jb0Y2M21Y
            UnlSclVwK1U4RkVxNmMzM24yN3Q2YWMKPcqzmI6FC8wJMN/UcX2XIUsnNiNFcNCM
            LUTbtUw82GeFXJrWl5IxMaiu4Ahu6Cium9jwsRihVQaC6Auc71+Qng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T04:45:25Z"
    mac: ENC[AES256_GCM,data:jzTqxZaPInLpWbNJD9Z5DLfetwszqd550hXQK3/ADQ5XX9bKO6YoSvi71eqSY/5vbxXlo/4e0NapgW4KIxNwuba+RCamUBXV5RlQ9+U8GLp57wDrkzOWlIjZSkGVgYF5qv+3vtUU1/wuH7gRDKS5WYd2MN6Fa/z24TO4TDv2ovM=,iv:L2AvlbyiP9ZuuYjy0gELOJmG+hMRUVjZV9jHbJTezm4=,tag:yu9CwjBzZl+72VFPAKzgeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
