# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:OJwHBdyRMepOqdSYidj+KExDpZzSSsc=,iv:bmPvTnZDJogwanNMCtfYa7kRQljJf2M54tNKO2HGG4w=,tag:JIFmvPJFLO11+zcxc+JCNQ==,type:str]
    api-key: ENC[AES256_GCM,data:n1Kr4+SG8FgcEuAY1rdmuR0LW41CE7WQ4LmMi53KC5TwONZYEg==,iv:bUkI+x3GQri+D7GRMaekGI2tiA1kOrBa03cwJ9qY2sw=,tag:HZfPWpPrZn3YsKsNHcjCcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa0N3cEd3dWJocHZXMXgv
            OHJRMEZNa1lHQzVCMW50aHhJaExiZnpVcEVVCnp0TVl6VE5uYkF6SVpMN0dvZFJy
            Mm9hZUgxemRhdE9OVDM4a28vWGhwNTAKLS0tIFYwellOUVFhUEplblE1UTUrVDd3
            L2lvOXZhOVIyNi9pdzBrN3lyc1BLQ00KPoh8aW+AgyRd6GaN27HncySGBlxMuOmY
            V4pImFqv09nPtFFwa3+MXkhioO+Q0wlBiKct3TQd7ZAAsATGHu5eoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T04:56:15Z"
    mac: ENC[AES256_GCM,data:jFjDJpvj+GER/goUlnpDoAFyjPLs6NsoYgLBCmXxigXTNmJD+ybJLmCPCEllajO88I3vqCvEB0z/cQDuXTZclS2JevCMof3mrD7yaxv5+9dCDfSefYl7s2Ir1QFx/GaMwxUhNeGIjixN4S3tYo9sFNeAnzTvAB9lKTgdBHQ+vx8=,iv:MP4hLchZck1o1w7eidGb/Y2+8QaP6LX3oU36lf+Srgc=,tag:8hluaEYen0nMfrUem5XadQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
