# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dnMn2+8nfBclfQ==,iv:uLbJXe+ZHvWBgdrnjsvUWPEQgWKs8IZq3aYzg54mzcs=,tag:msnSzi8kpr99+sRTsDvCSQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:P0wCSouuxqWLDF2cIevmeJQp663jSZo=,iv:b8DAMxUn8p3FOQ+3umFW7/kZc6YMiXKCY5VAnbBOSLU=,tag:78Bhw1/jIwXQ3Ot1dneEUw==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:4Gwl6e/ZFfbBmqDr7+wGeqx3LXFnfumEkFYhYd19fUyDGWpWHuK1eUuDUgnE/QyP,iv:YOL7SuvFMsnRUIL0N8McEi4FYkqDoY/qP/zYjg025Ew=,tag:VhHvkBFfD45mZJfFe5g6hg==,type:str]
    SECRET_VAULTWARDEN_EMAIL_HOST: ENC[AES256_GCM,data:4duLlcUH1LieClOCd+ewKQ==,iv:lbgDdGQFYluSHmaGAqdUIsVovMP94C++kItuoDqzauQ=,tag:pkJ55axd+3PMu4WHgSRC5A==,type:str]
    SECRET_VAULTWARDEN_EMAIL_ADDR: ENC[AES256_GCM,data:nfkupKBkjn+JTJF1JTNXuVRd2Pe2,iv:Q/W+01gXjKSLH0sTl//m0S0EwKqcCroSLMAYbN9QNcQ=,tag:pGY2OlF2T3LKpOIPXxWPHQ==,type:str]
    SECRET_VAULTWARDEN_EMAIL_FROM: ENC[AES256_GCM,data:qZhQPOpTlG666dLNdDpLQA==,iv:PofX4fcqEyJCyZRW250K2iPvtxCuwk9E7E/2mwYVFbE=,tag:oRcbXyGEMnWj/0csi33e4A==,type:str]
    SECRET_VAULTWARDEN_EMAIL_USER: ENC[AES256_GCM,data:IQ6IIDBWAxQVVQ==,iv:k11Z0qZMoJPDrmZZ+2B4/weOQmzjanGhY9ePbjJ9ZnM=,tag:a8TwctLYzZZTo3VyZp+3XQ==,type:str]
    SECRET_VAULTWARDEN_EMAIL_KEY: ENC[AES256_GCM,data:a9qJ6GmF+vcnNVnTrINj+qQvDI989TjEcH/63yrkXRQ=,iv:VGDdvV+XUj0xDqcskEbo++HLClofIEy0Kwu74eVx9No=,tag:mItPJHT0g4GZYf+stG5LPA==,type:str]
    SECRET_VAULTWARDEN_YUBICO_CLIENT: ENC[AES256_GCM,data:YWzIx44=,iv:U7OZSxxFOO7x5nGL3j0mHEdrmbF8B4V14O1a7rF6MXc=,tag:A/+4degakgvhiyLYjHpLZA==,type:int]
    SECRET_VAULTWARDEN_YUBICO_SECRET_KEY: ENC[AES256_GCM,data:twZDLUpiNzg6l7L/kAdVeMt+V6FPwJtAGW028g==,iv:uEmudWfrSx08lYXWvgRYxebSE/BaHWt+8LaunsgpC24=,tag:bhqsOuhFoLU8C2KCTG3TAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u9qu2c4mc3pcave6smwyv960vq4tjnrdq76k8aq7n6xnl9p6kpns08jkst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UGhDdHdBRXF3QW1NaWYx
            NXpoSGlsZkN2RHo5bkZ4VnFMR0J4clhzT3hrClVBclFIMmVzUlc0MWhIeTRJT1V0
            NWZQSmFDaXJ2VXhMNHg4U2FLdFM0RDAKLS0tIHM2R25LN1EyVG5RUWpWZUFEV2Y0
            Z09vaG5lbTFmVTMvamovNGVmLzRTT3MKBam2ca82sOvnlugshMG+aQKGQVDqjAMc
            bJr6Dxb0Gat2DTUmWA95dG5QxCGT03GNo6iakkEa+EStd6Y6CYVOiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T00:11:34Z"
    mac: ENC[AES256_GCM,data:aOgMp1saFl7mEnIAY5F+UqSLbeerS+iDcNlw8eZJ5Ct2Gt/RdGqa2irCnG84QZnO2rzfA5DIo7EuwNOqUag9aAVFNXt63Nys+Lq2iPAyP1cpMtVQdzVm9RwujpdIDVBxbiY3KFy7x3AYzbfMNhR8GV0LbFJzCrFM+GDNk8HMEMc=,iv:olF2CpgFIAy3k77C+esArV4+stBTwNWTdfUyHGVAjgU=,tag:gTN3uVKRt6uh5ESw60vREA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
