---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Phoenix
  METALLB_LB_RANGE: 10.0.0.100-10.0.0.110
  METALLB_K8S_GATEWAY_ADDR: 10.0.0.100
  METALLB_TRAEFIK_ADDR: 10.0.0.101
