# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9GXjp6hnOuMbhw==,iv:mGLFqKbz19/vpZz+VAA8WPDfnFvt3OWnVmyn9843PL4=,tag:tUq8wQAnp5/qebUjM3l6/Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:geaCE9niUYrhh+yJJsRR4/bqSSgX2V0=,iv:e66v9OaUzcvDXEjVyhjIwom4BvxcRovZYZr/ewfEscA=,tag:Pq8VdXLSXCde+Owt/5G5Hg==,type:str]
    SECRET_FOOD_EMAIL_HOST: ENC[AES256_GCM,data:7KkIeZ+ePXUaPtGuKURrsQ==,iv:225+Ldde9I+lf+R8DkDi5EWFWCOhRt4PbwaDEdGHuGI=,tag:T18ew749cnH3yEZGjjXL5g==,type:str]
    SECRET_FOOD_EMAIL_ADDR: ENC[AES256_GCM,data:I8WbOIYOdtkkUb4fOPvaVg==,iv:6OZ+uu19LYQx9TPGtslupEuJOtMxK1s8dBbfgNlnLlc=,tag:firu6WIU4Qtegbqn8T27yw==,type:str]
    SECRET_FOOD_EMAIL_FROM: ENC[AES256_GCM,data:GjwYMT0M2pOPg5t/,iv:TG+5c/Bp0nRbOhpn2OPE8EnKeSIzSWTvfrB/SBceg9g=,tag:oVWlJimrQF0YnkqNVL6JSg==,type:str]
    SECRET_FOOD_EMAIL_KEY: ENC[AES256_GCM,data:tOL5yXz4TXjfki46eLxuAzIDb/4okzeFpdycDS2M/is=,iv:loxlz771h6vS6ly1m9JjynjEf/QI79Q7XwQzenBKO8A=,tag:FFiOPmFJHKpvXQPPPQH7Mg==,type:str]
    SECRET_FOOD_EMAIL_USER: ENC[AES256_GCM,data:O1wTwgpvLPbkpw==,iv:Dg5KbjxG+3q+4XKPzQtbvyw7ymgIMGKw+3KCgEaaXW0=,tag:JuyYOeHettW8WQ1L9a55SA==,type:str]
    SECRET_FOOD_SECRET_KEY: ENC[AES256_GCM,data:t0Skh/cj/1MMQ8kJQLM+BBuvlbpjT2pZO4jPaXQXAJ0=,iv:5XpX1MNzlT+qKRwdndM6h90OLpFniS874V+hlAgoRCY=,tag:kD5Ov9ZYE0uZn61mo9bB4w==,type:str]
    SECRET_HASS_DB_PASS: ENC[AES256_GCM,data:I81BBhXwSHz5TAXxUDZaOTgolVVI6CRhOKOs/JIeEt4=,iv:1GDINoOEfztt30r38w+KurQVc9tqo90YnBlP9cg0tPo=,tag:9/UNbvS1fPyl+OST6yHsiQ==,type:str]
    SECRET_NFS_SERVER_IP: ENC[AES256_GCM,data:8YFxtLtfy/mn,iv:La1AnADf5QoKDGOzxRC+hNrhsWzNgXZVxY6NYHX6NGE=,tag:lUDBLH7nTzeBFU4IrFfxZg==,type:str]
    SECRET_NFS_SERVER_MEDIA_PATH: ENC[AES256_GCM,data:rMjYdJK5eRJeDZiYQV4P9Ro=,iv:sp6L9VNqtjoA51yJy5fPtpnByZ5hSy4W6QLc5JsfEWM=,tag:jYv663SFcYoMPVfi7eXOlw==,type:str]
    SECRET_NFS_SERVER_ARCHIVE_PATH: ENC[AES256_GCM,data:XC/7kKO4VvFX04XyC5TJaKv3UcEOng==,iv:56gQF2FEUWgBZ9OCAwe8SZe5VKq6v4WXfsEdTqQhsSA=,tag:ji/0K6vflbn5t5h59CQR0A==,type:str]
    SECRET_PIHOLE_ADMIN_PASS: ENC[AES256_GCM,data:dic5LRkhp0zplbp8151yy2sn3LA=,iv:wLDtRkbHol4scUyz6FX83QsJGfvGXaEuyJxKC3DJwHk=,tag:Ki+WwXXofSTPad5HE9sKtA==,type:str]
    SECRET_SERVICE_USER: ENC[AES256_GCM,data:VAV1xg==,iv:RxN2yfUNzxagazzKSkJYTjrP7L2D4vwcLe6Jhfv/BMs=,tag:hBGt9E0iD9zp/vIiuo7cbw==,type:str]
    SECRET_SERVICE_PASS: ENC[AES256_GCM,data:PdcqxLWi+A41ArjWeeJasRE=,iv:6o1vpS06NnKu2EDjFdXGoT6h3nMTH/8nvOQHKW4HlSc=,tag:DVQVweymv9vfvJbzx512cg==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:SMR+jJTbUMYC618kQBkoNL4E1TN0Wtnsi640axVcwFPxFcrWuosBezoVQmE8U+rw,iv:ax+RyNers35b94xL8T5ftw6Ybb0Tve0JkGr1HqGHywA=,tag:E1CuIEZ3OBJwBUVG8My3zw==,type:str]
    SECRET_VAULTWARDEN_EMAIL_HOST: ENC[AES256_GCM,data:QhQ0YrR3XPovrNPDanhZDw==,iv:ibk31h0ZpBbNACmum4jpaEYAeSSYuUX7Gvt0RLFKB04=,tag:DFoRs5OPnjGeUdBWA45ZMg==,type:str]
    SECRET_VAULTWARDEN_EMAIL_ADDR: ENC[AES256_GCM,data:UoYxWY+dI4EG7ha8t0Ajqw==,iv:+esIeY0rbGFAFKObGkreYRB0SIkeJDJJoKqTl0K5LYk=,tag:7TrktXbrsU2IDncDyG2Wug==,type:str]
    SECRET_VAULTWARDEN_EMAIL_FROM: ENC[AES256_GCM,data:M4iBCaJq2sYvQcUC,iv:nh1c0wvvVx9k+YPzXdM73FVHd/Cl1E7JGWFveN30Boc=,tag:KEaUEMJ7YV3Xy9o3GZwUTQ==,type:str]
    SECRET_VAULTWARDEN_EMAIL_USER: ENC[AES256_GCM,data:3xxR7uDNx328RQ==,iv:m1CxqKUBEWVWy/3NpY+TX1MUVzVD1TKR1yY9V364aVI=,tag:HU6aTyKDbcp+hMlJELyoZw==,type:str]
    SECRET_VAULTWARDEN_EMAIL_KEY: ENC[AES256_GCM,data:fHnilRd2v2P0VyF8t6u0A1FvBwBRnzofaw8IBO+gBKY=,iv:FMEvtEJAoc5W4z0JqfiY0LzQMqA69oO3La8iUSEcV+M=,tag:9RQd9XWf1qxAghn4nmb5IA==,type:str]
    SECRET_VAULTWARDEN_YUBICO_CLIENT_ID: ENC[AES256_GCM,data:Gvh+Xgg=,iv:yOJLryNzyG9YGTfLW+BlcNBiooFuDuXTCbckF9GOyVU=,tag:WZRxYhQBlo/p0QPtUYcTLA==,type:str]
    SECRET_VAULTWARDEN_YUBICO_SECRET_KEY: ENC[AES256_GCM,data:2PLFVuhSj3Nr3A7JOgQoCJJcepErYTGKSKqn2A==,iv:f9cqT2lp3dyN87gWLVgStqiyJtBkP899KhTP+RZNlBI=,tag:2m4CjpNUfHaOXPNK67Z7BQ==,type:str]
    SECRET_VPN_INTERFACE_PRIVATE_KEY: ENC[AES256_GCM,data:1spSMCHKfyzXpE6SioLsCqPmhzrYh3yfi/cghtZtNDTZ+pljpFhyL6S4O7A=,iv:26Aj5ocQ9a1GW5MY8wvi/OLVyfcbzIfSKqp4Pdj4oiE=,tag:VRfZAUoJYHK9wOJbH8fBSg==,type:str]
    SECRET_VPN_INTERFACE_ADDRESS: ENC[AES256_GCM,data:6N3t9ZI1eFZgxEw=,iv:aw33qrMv7iOj5FeQzFoAveVsUJIc6fpMuUiIN3a3X4A=,tag:yEZYLbmjp49Ij5CqWDwxHw==,type:str]
    SECRET_VPN_DNS: ENC[AES256_GCM,data:y+VK1wuAcyE=,iv:ZPVEIh88HVe6tBnvWiiIqtPdYw+nt/PUP2rX/kfO6MI=,tag:0WTjQfUnAGCyRighQvYdng==,type:str]
    SECRET_VPN_PEER_PUBLIC_KEY: ENC[AES256_GCM,data:M4AvK+adjHHI1+wNEhh+JP4a817M9FCwL2u4VNdxKkQgJs/riHGNxNIAplY=,iv:r6rTIyI3fGJT5ApujbGOGptiLev7jYYdvAkrBtz7fDU=,tag:epvQlCwYbl70mWVHny5zug==,type:str]
    SECRET_VPN_PEER_ENDPOINT: ENC[AES256_GCM,data:vLUd5+RyKAbLh6M/bZ1Bpsw5NQ==,iv:RUxfDHrIQnEjPteNPOTXZmFpxb5obxBAOnv5L93V5bQ=,tag:gAml29/fN23V1HCHud8z9g==,type:str]
    SECRET_VPN_REGION: ENC[AES256_GCM,data:0HX/awBqFDoZsA==,iv:SyeOiA1zeSyKNy9ugULOSGiLFMwRy1OiG1+OmBuIbvE=,tag:eKhOZGHB3D43g8gjJQFpxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNWNsKy9KdTFRL1RQMXpE
            T3pCUUpzMDZPSGtuTXBleDRGcXJkVHdpblJZCjV6Q0lITWxSekNUMUJ3Vk5BKzc2
            akhEMlFjb1hhdU1nOUtucGhuSXQrZG8KLS0tIHBNZnRSU3h4bjc4dlFSK24wK3V2
            VEE3V044bmx0aWZzaW1IVDNIVjNoeVUK97hrJW/YVfCzsvW2jXtg4YCRXZU7C3n2
            i9HASu9/bPCB5WWG0t6rcwBRnn1EsClw74pniwhF3O/TIhX/RHX30A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-05T18:45:25Z"
    mac: ENC[AES256_GCM,data:m7ahG53kLPapJXr7rQIJ3UOzRO2/c/tAHW/shlhkhLny3qGJFjTQproav1Bvv8bfqWyDyPlBv8LVDsTOMtbjBEV+0uK7ZrEI/elnv7FTnx0bSOOQ+pIpvw88f8aNy7/s65M8FEYHq5oTZ1OmmIDR/4oZZxrenEw3Y7OjMb+Y+Pw=,iv:M7Z5PGfInnnQBrN24vg77RRdLO319FjUDW9CgIqLyEQ=,tag:q9uIR3+jzc2trQ1f+jp9RQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
