# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:MGh0yRxxd8x4Fw==,iv:8pZsAT+TJ5wwVTD81uQmtX+HgNAS2fCJaid5PBBsDPc=,tag:xoXk3EaacuIliuU+/5RhJg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fNFuNkSxE6TIbZTaX1CGWBiCXfd9HQ4=,iv:FGwSkuCi/QM4vNj1YC0Wjn3w2aiIlniQc2g0eYa7kQI=,tag:tWy1oHheTdDx52hjUlvOdg==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:KLtz4Qo9/VAUOdgGLUDTW/jNO3z+kFqcTTBgBQReF9JraW+ZOnDfTnuULarzyo39,iv:3a1bDrYb+zxrt41+bBy8hGXk036YqONOb/gFkJ6piKg=,tag:m6DftN8gZic3rdR8khbSbg==,type:str]
    SECRET_VAULTWARDEN_EMAIL_HOST: ENC[AES256_GCM,data:a0gSRG1jm2x7tSDuXBhUHg==,iv:v4z9CUWSY9TrAaEv99aUrn2Nmq1TY/FtVVhyR8irA1A=,tag:UXsSblTthOJFGYBa+IOg3w==,type:str]
    SECRET_VAULTWARDEN_EMAIL_ADDR: ENC[AES256_GCM,data:WgF085quAV6m3V9sXBwdzg==,iv:ImL00BFyD5E+Tvxw03a8XWbigGMhtEvtDytQ9Hv08VU=,tag:S4HVnbGQMqAzynPIons4Uw==,type:str]
    SECRET_VAULTWARDEN_EMAIL_FROM: ENC[AES256_GCM,data:BS/7tc9PbGAJx+ge,iv:vcive0baQXMM0QAfyTb9GHbi6JRnYXFfv0pCyIZq9oU=,tag:xyG1bMvzN3QFDEPyb2X/7A==,type:str]
    SECRET_VAULTWARDEN_EMAIL_USER: ENC[AES256_GCM,data:ADyOwbY/5OdymQ==,iv:yQupPxya4EDR94isKtKUTCVL3VcRyB90z+P4lr0E/qc=,tag:O/KyYt581hsWYAn28j6/3A==,type:str]
    SECRET_VAULTWARDEN_EMAIL_KEY: ENC[AES256_GCM,data:hJyUxxbtC14ND+2jO0l885LDd7i6EimmBQEkOLFs/hM=,iv:Px4gGM89pQmunfWKzZIu7is5lIjY7sMPJlB4YGrfxc4=,tag:4/4pXwZCHcKz5ogAS2uyNA==,type:str]
    SECRET_VAULTWARDEN_YUBICO_CLIENT_ID: ENC[AES256_GCM,data:EB15fhU=,iv:vobjipz98sKhcpZcVDHDEN/g/lSXYtUn1zq2eML57uE=,tag:M8NhtnY1EfqgXwal4eO9tQ==,type:str]
    SECRET_VAULTWARDEN_YUBICO_SECRET_KEY: ENC[AES256_GCM,data:lYdSb5JQQN5VLfimIFNoqUAqiiTyLiUfbDkOCg==,iv:GNylcWfutbfOl+IIXwK+q5fregY1nKun4wxQ1taDGH8=,tag:tFM0YR70047qparOchgOeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a2pQbXdnV0NBQ0Z6WDdQ
            SlcwSS9uZktZVExXZkV1bjd6Q0IvN2tUOFVnCmN4Slc0aVpEQ0s1TnM5MU1ZSkdN
            Q1lpcTlSS3dTMGtucEI2aFJ1bUdlYTAKLS0tIGY5VlJ5ZTcyWktQYnljQ0xmWEY0
            SVVFSVhkTmRMOUdOSUJteXBSUnowaFUKpGuCWs3glhFvY/50bzH7q8blbLFt6X/Q
            a+2qaJ5Os92OagCm4c519Ih6XC3/5NovHkDgyAoAgpdOZdprKNQ0vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-13T16:00:29Z"
    mac: ENC[AES256_GCM,data:iNLY26JywnjGihzN4/yyBLXfywYdsqXsT4gsK+YFF6nKWRLOxn33yS0lqigt5A6L193Qk/AvnrKY9ont+GAAC437QGH1Y3VBlTrXxavWDH1Xk3XuVoOxhQKfp925p8WBN049kdgUA0vRIoFqU07lwmD5vdiywdwUdRQyQCkTsXk=,iv:HE2zN/tPp8s/uQi3DklwX71D+In9SBfCpXsh8m6gWl4=,tag:VsKJvOUTTx/yh/Q0kTAxGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
