# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-network-secrets
    namespace: flux-system
stringData:
    SECRET_NETWORK_INGRESS_WHITELIST: ENC[AES256_GCM,data:eoWRX/gBUEZumsg4ReqWWgXorrUL+ALMUWykvHQQHoA75NErbvpi,iv:L3aQdp8Hru9VelKxLe8tcAX8XDcJuXnyzaPpiWHAD6Q=,tag:JObLORAkyPm9sTKNh2Zbyg==,type:str]
    SECRET_NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:XAq2HClBFJ0Hxi70,iv:mxT7/C9CAh5L4PFSLIHbJheWdbXW+kOce4j5jWNvhTA=,tag:0Tmw+fWV+TPAWD85w63imA==,type:str]
    SECRET_NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:U5/CtXzKz9ZZynLg,iv:ZXL2EUQzVjcvJeTvu/io5gbsHDjn93CAt8Fa6K/I8WE=,tag:o1lQDzSx8OoraMCZHWIygw==,type:str]
    SECRET_NETWORK_PIHOLE_ADDRESS: ENC[AES256_GCM,data:swZ4gr3fdZUvVw==,iv:5lrYNdoEeRyIpXW3w5TfQmdhLrIjc5gnepA+3FZ8AXU=,tag:t62RrYG8ILseL+rCn3gG2A==,type:str]
    SECRET_NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:nuNCBx9F5tJ/jgY=,iv:/q//YGw7D4J8SzLfzA71FLePHX7BIkKaijA9foNBd1o=,tag:/LYIrceDxkpiGpbnofCDPA==,type:str]
    SECRET_HIGHSEAS_QBITTORRENT_ADDRESS: ENC[AES256_GCM,data:1RvFIMVsxVbwFg==,iv:T6rQabftibYXc9Y+6ms6JiUIr6SVS+ZBCt/qetaQ8eY=,tag:XK+VGkxXd5UcffOZjnw7HQ==,type:str]
    SECRET_HIGHSEAS_SABNZBD_ADDRESS: ENC[AES256_GCM,data:b6uXk3Vtw6rOGQ==,iv:taXJNC2cO8FNiUBNf2Et0PnWcX3DaO1W0Bwc5thw2vM=,tag:U8rKq8tpTEuM6bgBx7PbPA==,type:str]
    SECRET_LOWSEAS_TDARR_ADDRESS: ENC[AES256_GCM,data:LU+TTgI/G3JNxA==,iv:uBxCrGZrujbtQohaCtXdPOhGo9WBHEgwSR1EOSoWung=,tag:POB8AkZeZPW6/3zk2C11Qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGempvNnpVS0xBSWQ1d0l1
            NDJ3SXNzRXNXajdTL3F5VWtRMVFMSXRadDNJCmNiK09mZ1Znc3VoMDA5ZG1OVk5T
            a0p3TStaWmFZT2ZIUFdSajl1L2JqZkEKLS0tIG9oWHZ4OVdQVlVMNkF0SVBrV2FC
            blpXK2Vwc1VnY2lkN2dZejIwRlFrWHcKCr0iTjwlwrb/Ilj+wEzxJ9FqPCoixabN
            HgZv25AX7aSiQ+RoqiBlZkClslmtYP0F6PbzR839rzTYet799rhnVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-13T19:29:00Z"
    mac: ENC[AES256_GCM,data:23wG66rT7l5XSfy1iMZ/E9q4NGCeAy3WujleibFxcymR4yAdybkIoSlEt3FB5rzbJ7Z6sBk1NZUslHVytoOBaQxDgmJkZgBw3phxTR83zXf4rEjLi3UUkH13GPOcTcpV9wNcwjhvGAEgtCSViF3DAwd8UCqF4VQXkUR4rvrZM7Y=,iv:9tvKUqMTvNBq0fULS2DR4yTSGhYqJsXKCuRUEPQVySM=,tag:dS/zY7TCaYrYkc0Y+C3zsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
