# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:2BWZO5So0zV2rQ==,iv:5yxKuan61Nink9AUaD27Z+D864mJBd0XAgAuvua6gMc=,tag:Ic4YyHqa0X7pGsrwBBQmgg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:GpxeQcOYV4A1/UV9t/sKOOS0ENlRpw8=,iv:dRrouc3F/dOSSVC2glb2PTYiosPedJgtwSf199CMZWQ=,tag:/U19tmFVdtt8oS+GzvxTVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbk9McmJVcGlWNit6STVx
            YjU0RW9TaGhQcVlzQzBmeWVPNCtZWXpwRW5JCkpIL09RM1dxLzFmcDVrT21XR1pJ
            UTNwY0R5QW04ckNnMklPek9WZ1RKeDAKLS0tIGIxZGdGeUg0akFiVENyVTIyTm4x
            Z0RtSXdNNktTNmhaQ0lIQWU5ZmdGamcKTSzNmUM25QqhtYuJwOmcn396N7bj4CJp
            yoyxsnaydJd5ixk7cM+gG0x/AS2p0W4CVXIzh0UbXPQaJFf6EA1ifw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T04:56:15Z"
    mac: ENC[AES256_GCM,data:wYbsNp+0JbyPVGoRRyPV6hzodXcW2j2ERBouchr2SrLpGn+MEnQfITsBZHZix3f1JURmFBQrGCPWpq6tAFTmYxK549uL57VZiVfZ3l7YZU1VjMeYZWwr3fqkzraeOVTlV13fKeq88UM/3M+HAjfwfrANVCZbohD1POQ++w9taYM=,iv:T1T9tM2kMHKdrlBXiGFFbbcmDWEcG3vY2lyQnQ4eBdg=,tag:Ll4dYsbL/IWI2XkqitAhAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
