# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ysuhYgTZbBT0lg==,iv:w6UjZx20A+XxSux4Qt16XsL7513PsLJPoORPjSIpdFM=,tag:XvAwWdAxHn3/mRTN+55ZTQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Q6YjjeXK/tQ2f7cKt/u8XLSmzrs/gRA=,iv:fLPU1wgFeUyG1/KzLpqljuZIN7HBZQHvYht24hjpimw=,tag:s/4ePoiiRs5Sw+yZL4qxGQ==,type:str]
    SECRET_NFS_SERVER_IP: ENC[AES256_GCM,data:0pVgOZ5EJHbN,iv:Sv3KxtAeonApvMRs+CKhKr6aJ6hqCvzc15mJPxGsP5U=,tag:UqRZtB1WqAq7i8rarfYz5g==,type:str]
    SECRET_NFS_SERVER_MEDIA_PATH: ENC[AES256_GCM,data:n2Vc+j6Bn2jpXJXn3dKIdl0=,iv:eKw01089OxeGrnYnpj66mY5PU7HeRwB2Y5B/XHdou6I=,tag:w9qY5W15Wl/byQ6B71tFaA==,type:str]
    SECRET_NFS_SERVER_ARCHIVE_PATH: ENC[AES256_GCM,data:p8BnWYTTWq2eGRCHCULHPvjBf96g2Q==,iv:ojKpJDJICheA4h1JlzVmkVQEIE9kCUCIoIlY0tqy1ds=,tag:tsD0CQCMpuHQa7OGzxJwiQ==,type:str]
    SECRET_SERVICE_USER: ENC[AES256_GCM,data:qa2wSg==,iv:DhjHY967ffIkzYHei/4x1K0J3HF0CSCFx9Wct6dOYAk=,tag:YziCyu5pHRm55bGx7S8Www==,type:str]
    SECRET_SERVICE_PASS: ENC[AES256_GCM,data:3AoN6KmViTxuDH5AmM6UGj0=,iv:v30jGH4A6Fm5mm7zyN4N3YnuJGglZIJTMSODVing3EA=,tag:KTzUyeV0EelXBsn44sQPDQ==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:5rbxELacngC+CYdfV3NCSlUG9ET7KpXrXlq3Oski/tt9FjV2I2GnfpGp/zROgmQz,iv:oEEF2ItP9blksxdjnN8X1/F3xXXk2iGMNB+Jq4J7yOA=,tag:cwDZgLWE4Lq65im4ANKsTA==,type:str]
    SECRET_VAULTWARDEN_EMAIL_HOST: ENC[AES256_GCM,data:Qtbnmd5gxysjOB6RJ+Xwyw==,iv:/4DJlKfkMM3vxlpRz3TY570gsv1ljW6GgmT9CxeAhM8=,tag:h7Ueh4JWIZkoQUWkGyHcGg==,type:str]
    SECRET_VAULTWARDEN_EMAIL_ADDR: ENC[AES256_GCM,data:86cUIpyKrweYhO+aWF3E8w==,iv:6BIpW2ao9sQbCd4mHsL7JDViQ8B6AHYq2pVqzvooZIw=,tag:DPedJH5Wptx6tWAVVJJDUA==,type:str]
    SECRET_VAULTWARDEN_EMAIL_FROM: ENC[AES256_GCM,data:K/w6F9tor30ttOy9,iv:DhvztoD8O0EPXdtiDfqljK2vAWZr317ElFJ6mixfhYE=,tag:ln8mGw2R96LVaDCwyvJmeg==,type:str]
    SECRET_VAULTWARDEN_EMAIL_USER: ENC[AES256_GCM,data:sWNtLoSsO+d1JA==,iv:hpJiWhpUddYliTIFHxRnMFZjYZRfN7Mf5zX0rXOn/uU=,tag:/r2Pdun3moz3U+68IZSZfg==,type:str]
    SECRET_VAULTWARDEN_EMAIL_KEY: ENC[AES256_GCM,data:PeydAUBQxjwys15FAQb+bxrOvwHD0RofEtmtEQfdr4g=,iv:tZcJSz+ymkZDPbX2H5mTqBmEwJ78hk3iO+4jYIrl2os=,tag:Zzmqp44lyI0OgSJY99bEkg==,type:str]
    SECRET_VAULTWARDEN_YUBICO_CLIENT_ID: ENC[AES256_GCM,data:Ted5auo=,iv:tiNx67OopG5fvITVv07eqEwN7zJK7vdWrxuBY99D9EU=,tag:lVwox4vEyoqIOE3vEkr8/g==,type:str]
    SECRET_VAULTWARDEN_YUBICO_SECRET_KEY: ENC[AES256_GCM,data:cm9a/AImHu2eOAdY1OlNQRrgU09Ro0JeMYo7+g==,iv:IaidE51ho7IpAluaTkET0qA+PCmBbJ7epXviJTTdYJw=,tag:7TZx2/+0ZsCtDOr8BHy1UQ==,type:str]
    SECRET_VPN_INTERFACE_PRIVATE_KEY: ENC[AES256_GCM,data:ZNTMd3aCYmHfrxblxjdZITz9QsyA6q0lfLxZaTAtW85fBMNxeTwfnrj04vY=,iv:/RNsaMGf8l/pyIOBcLA4NT03s+pm0cT/tMMr5RBW8J0=,tag:Ua1RlyvI32RkYaydRt45rg==,type:str]
    SECRET_VPN_INTERFACE_ADDRESS: ENC[AES256_GCM,data:cM8wAjibmx1Zo+8=,iv:Mn/dIqnxNEm802GWWiImxtzWmOWkw0YtJCqxKt2w9UU=,tag:hckezALVd9tAzxMi5CUZDg==,type:str]
    SECRET_VPN_DNS: ENC[AES256_GCM,data:syD4taW3MQs=,iv:wSe0KkT07XWlve6m+inu6bnleXJFn+h0zmUqFroKXmk=,tag:kOO/PMQG0u/89/YanQx/lg==,type:str]
    SECRET_VPN_PEER_PUBLIC_KEY: ENC[AES256_GCM,data:r6sVPSozMLdguOrjkeYRQYHKuTVA9qKWaxR1g3msIwFNMFqRDRWqkPaCtE4=,iv:XebexqGnX1r6EHfa6WH4XK37o/RRWZqB4WynXHKTyGM=,tag:EXxa36ShtFyADFVCj10ouA==,type:str]
    SECRET_VPN_PEER_ENDPOINT: ENC[AES256_GCM,data:VSi2i6QZL9cbbzrNRb/ZN/YHsQ==,iv:T/nQ48wrfCBt9+fARYe4nrGaMBEGPmJb+0sM/YYvGlk=,tag:ahMmVbS6uaLA6JkJuK2JlQ==,type:str]
    SECRET_VPN_REGION: ENC[AES256_GCM,data:lLbvieR0svaC4A==,iv:QtvV7eL3EuWMDnfWkwJkIynwMw4pC0JkXsjU6Ukg9X0=,tag:zt3vuaKo9X3xTEp9OR6Pvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwc2ExdHFmaUwvbFFPYVZW
            OHpuQVhXdk0wbk5OQXE0eDdiUW5XYnhJNXhrClkvRDROeVF2NTlzbVYvdjBub0pj
            SEIxbWlYOFZZR0JXY3lUMWMrak0wVEUKLS0tIEZybm1OakY3cHcxWWQwSnAzY1RT
            VU45ZnNFK016NlhEQTMxMmdSL2Zwd1kKGZcXgoRAvvnAZgUGQBu9zZhbccvXgoEr
            B/ItUlHgC8Lk+IS+6oEZMr7uY2X5GKLZoIgxKX7FdoSjT+tOh1+Dbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-25T00:28:42Z"
    mac: ENC[AES256_GCM,data:aaB3lL18UqoCsu2sT/BBKnkcg92BUNZo5LUKNuXXf+5SCgwh0VPNzymj13VxjmFs1pTvlqOBXwfxLo9F1jGdmcPgkpmMaTvCQpWy6vTW8GAenBkBeDikNqT12u85xJUWkEAHIRkEXEzZiVnCtX8AboxjwckXPNYMmLoJu7HqWJc=,iv:BYVNO+VhJ20BNnfay7rzl869w9fnE//oUdAnY8vG3CA=,tag:EHmK/xk+kIVXUCZv9ldlTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
