# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:J/tQLmTSx3fI0Q==,iv:X9XmJo6hzlhw6wdRoNXjqEHfYLiY5IUVsp2Nq8DfOGE=,tag:94VcuEdSTB52BsfA+jU+Cg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Sa5lQg1FE3sedMX7s3qMN8MijA610Kk=,iv:nmT1nL7K8JLzkeNIvse/ALhVt6vW6RlO3u3AQeSOgw4=,tag:AEj5kZnvD3/1AZdB4WZLTQ==,type:str]
    SECRET_NFS_SERVER_IP: ENC[AES256_GCM,data:AsZln4L7SJSM,iv:B56YfDoPSkYvV+zysgrZriqCroIizvYIkRIgxCHgA/c=,tag:DqOCLRt7VLO+SgEjeLRPIw==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:MN8VRezwsJTO66CorLGy8fdKil29FutU8joGXsGI5RbmoyqsbYFxkyxJt8EaG2J1,iv:lmrDhKKhsHjlYktS62vKiQqADnkl+dHsncbcKwlVFsw=,tag:xhmnDIMDkuCF/yymSTqC6A==,type:str]
    SECRET_VAULTWARDEN_EMAIL_HOST: ENC[AES256_GCM,data:d673HcoCznuEaNMMoqDKfQ==,iv:JrnoBMmgsmVi6uG426sJ85gLKSaDqWsMZuBOYrBjVhc=,tag:cWUA401v//h3WiZ7QOloCw==,type:str]
    SECRET_VAULTWARDEN_EMAIL_ADDR: ENC[AES256_GCM,data:+NJdZ1zujp54hCMyZh1v2A==,iv:dTSo/39bpCTWUUaJsp6rpKVPr1DXnQiPA4Ge33UAg30=,tag:piPkENlGA3G1+rMYGM5wzQ==,type:str]
    SECRET_VAULTWARDEN_EMAIL_FROM: ENC[AES256_GCM,data:GLXeu7wlTYNud58L,iv:Aihl+mMtUFbZMBtclmtSYF+HQVFU7iFE3LtTbnok/GA=,tag:th3ocW0D1GI5tbmg9TzVtA==,type:str]
    SECRET_VAULTWARDEN_EMAIL_USER: ENC[AES256_GCM,data:L3hFou/mE8Z1RA==,iv:vtU5mOPa3Bb4cO2aX/Kw9XQNVVfEBVUGAeY6XtVzMcI=,tag:Mlt+yhgLTRPRrIsfbcmJBA==,type:str]
    SECRET_VAULTWARDEN_EMAIL_KEY: ENC[AES256_GCM,data:qsCQlu2jBNHx805vy8iFR9w0g9TgGoRGoWKR8SxZwFw=,iv:esSiLZiE5Z2uNEu6PFqZ0CTP9SyteFVfciKU5SWw6xY=,tag:HoHn4F5sh6NoueEWr36vpA==,type:str]
    SECRET_VAULTWARDEN_YUBICO_CLIENT_ID: ENC[AES256_GCM,data:qM6CV6w=,iv:kiFxop5MgA83TCLxF+/nZapnZ3zskRxh86efFtVjgGs=,tag:VxT8ZwryoIEBDMlHr4TBZQ==,type:str]
    SECRET_VAULTWARDEN_YUBICO_SECRET_KEY: ENC[AES256_GCM,data:YEs5jV5chgmSW4Is/Mi44Q5coDMc4lvaP2c0wg==,iv:d7WGnSWqmw+U3K66jw20tdE5lpHnCXHGg7bfThyItrg=,tag:wRUyIGQVHJNBT9Pb9If4IQ==,type:str]
    SECRET_VPN_INTERFACE_PRIVATE_KEY: ENC[AES256_GCM,data:zkssATXmcRVTOidBIGiCX+3+BNerBDHKllPyfvta1503xPFo70cJ17Jmt4g=,iv:GjtXjGMC2QsWwokqJjdnJOFYNQ9KawB7O782IC5505I=,tag:R0JbTxoRpbPwk1BxHu97hg==,type:str]
    SECRET_VPN_INTERFACE_ADDRESS: ENC[AES256_GCM,data:1caTUQWspxHELiw=,iv:lxtgygpVLxJVhH9OKt2rbJTpsJ2fzrVjNw+4C0aazTQ=,tag:3qF3aF59uAwOrmsAal+VvQ==,type:str]
    SECRET_VPN_DNS: ENC[AES256_GCM,data:KUSZckj5EJ4=,iv:S+Fe+rcPKHcBrskM687LDhXCdqf6Kd90ILem4NkJ5Ho=,tag:0snXDg+ipIbISv4+C6ZdVg==,type:str]
    SECRET_VPN_PEER_PUBLIC_KEY: ENC[AES256_GCM,data:y6ojk/x973q8nzIMnw+iIBT+Euqq69ZbNuISN8uOt4Hzk/Yl1Yy6AsQhnfY=,iv:P8bi7H3M+JX4SiRTNLejldICXav77sjCZVASHzlDIbY=,tag:v9KoPsVjyHrHQm2re1x+AA==,type:str]
    SECRET_VPN_SCRIPT_UP: ""
    SECRET_VPN_SCRIPT_DOWN: ""
    SECRET_VPN_PEER_ENDPOINT: ENC[AES256_GCM,data:rD6uKX+vVJQbTL8qnhPbMlZWWw==,iv:msyGNIkiK79zFtlmsMC6oG3U44jKeaa1gmR2fEYjQEY=,tag:7CwOp/BJR9fzx7lHreUdPg==,type:str]
    SECRET_VPN_REGION: ENC[AES256_GCM,data:6F+x3u5JcxLErg==,iv:K96stcBdCaWoEsIajyjLBp6x3SleJtHbPW2iEXQHO2k=,tag:1iJVdjti7L2Ax6PGrNgV/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiY0lZSEdIcVAwNVBONnFX
            Q0lERjluMnVPVzVYRWVqM3ZCK3NNYm1pVEU0CmVOd2x1V1ZJVHlNTlM4ZksxOGZs
            RHZzTUpMSkM4eFJSSldTdUJBazVENTQKLS0tIFVvZFFITzZCdlpOR0pFbVlwMWFI
            d3hhc0tYR3U1VU9mRE8xZDBpTEpNeVkKyk1dDD0qR9IXHAlKcBT9FA5o3aFM00ji
            trRNc/gDYQht7JLUkGTqX2J71Fo/8WlKEPbtkyv2CFKUbdZXx+J3iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-15T04:17:20Z"
    mac: ENC[AES256_GCM,data:lDNGSimO5JQCZptrEo7Mbm5ol2RVb61QAZKzcwCNdvGfIj1hrwqY4k760FQhgK1MktUU5a2g80NMG0O2vc8OCz1vVY5Zjseb0LDwovh3YLulenDCr+CCoZbqzHW4iTItK1xhcC0z4Vh0zZ6LY8SH7FaNvRglgLTAYjp9hrlQ0Ps=,iv:qHk2fAdwbdEVkz0dd+qRFHsZ+rvMq281n8WMh1xo1q0=,tag:gmQyU/RylRPag1VgzLIaDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
