---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-gateway-config-v2
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
