# helm-release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.5.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  # See https://github.com/k8s-at-home/charts/blob/master/charts/pod-gateway/values.yaml
  values:
    image:
      repository: ghcr.io/k8s-at-home/pod-gateway
      tag: v1.6.0
    clusterName: ${CLUSTER_DOMAIN}
    routed_namespaces:
      - highseas
    addons:
      vpn:
        enabled: true
        type: wireguard
        wireguard:
          image:
            repository: ghcr.io/k8s-at-home/wireguard
            tag: v1.0.20210914
        env:
          IPTABLES_BACKEND: nft
          KILLSWITCH: "false"
        configFile: |-
            [Interface]
            PrivateKey = ${SECRET_VPN_INTERFACE_PRIVATE_KEY}
            Address = ${SECRET_VPN_INTERFACE_ADDRESS}
            DNS = ${SECRET_VPN_DNS}
            PostUp = /config/up.sh %i
            PreDown = /config/down.sh %i
            [Peer]
            PublicKey = ${SECRET_VPN_PEER_PUBLIC_KEY}
            AllowedIPs = 0.0.0.0/0, ::/0
            Endpoint = ${SECRET_VPN_PEER_ENDPOINT}
            PersistentKeepalive = 25
        scripts:
          up: |-
            #!/bin/bash
            echo "up"
            ${SECRET_VPN_SCRIPT_UP}
          down: |-
            #!/bin/bash
            echo "down"
            ${SECRET_VPN_SCRIPT_DOWN}
        additionalVolumes:
          - name: data
            persistentVolumeClaim:
              claimName: pod-gateway-data
        additionalVolumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - if [ $(curl -s https://ipinfo.io/region) = '${VPN_REGION}' ]; then exit 0; else exit $?; fi
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 1
        networkPolicy:
          enabled: true
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                - port: ${VPN_PORT}
                  protocol: UDP
            - to:
                - ipBlock:
                    cidr: ${SERVER_CIDR}
                - ipBlock:
                    cidr: ${SERVER_CIDR}
    settings:
      DNS_LOCAL_CIDRS: ${LOCAL_DOMAIN}
      VPN_INTERFACE: wg0
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_TRAFFIC_PORT: ${VPN_PORT}
      NOT_ROUTED_TO_GATEWAY_CIDRS: ${SERVER_CIDR}
      VPN_LOCAL_CIDRS: ${SERVER_CIDR}
    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.5.0
      gatewayDefault: false
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: highseas
    persistence:
      data:
        enabled: true
        existingClaim: pod-gateway-data
