---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planar-ally-config
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
