---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash
  namespace: deepseas
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: stashapp/stash
      tag: latest@sha256:24dbd76071745be0c4e75f730aa7ac2b37cb2b2918eabf8559643196b3b7a64a
      pullPolicy: IfNotPresent

    hostname: stash

    env:
      TZ: "${TIMEZONE}"
      STASH_PORT: 9999
      STASH_STASH: /media/downloads/other/
      STASH_GENERATED: /generated/
      STASH_METADATA: /metadata/
      STASH_CACHE: /cache/

    service:
      main:
        ports:
          http:
            port: 9999

    ingress:
      main:
        enabled: true
        ingressClassName: 'nginx'
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'cloud-download'
          nginx.ingress.kubernetes.io/whitelist-source-range: "${SECRET_NETWORK_INGRESS_WHITELIST}"
        hosts:
          - host: 'stash.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'stash.${SECRET_DOMAIN}'
            secretName: 'stash-tls'

    persistence:
      config:
        enabled: true
        mountPath: /root/.stash
        existingClaim: stash-config
      media:
        enabled: true
        type: nfs
        server: "${SECRET_NFS_SERVER_IP}"
        path: "${SECRET_NFS_SERVER_MEDIA_PATH}"
        mountPath: /media
      generated:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 10Gi
        mountPath: /generated
      metadata:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 10Gi
        mountPath: /metadata
      cache:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 10Gi
        mountPath: /cache
