kind: Secret
ansible_user: ENC[AES256_GCM,data:w7DM4g==,iv:jDhVsOWJO8zEJ51/PV2S224xXGFRepJJy5BNs9jG2s8=,tag:iFtusWP+yK3igF0syWzdOg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:yXORDuBwfAtAtBKIGbY0Z4YbN+UK72cQ7NqjO+spqj0=,iv:XsEUHZbcxlJWWnnbezQ5CQBNiH+lrQ+uo4NFs4QqhG8=,tag:8jMoFUZbg0M+O7BVGUhjzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcmxZT1RiK0xoTCs2WGFj
            QkorQ3grNXRMNXcxdmlIbmVrQWVXTEhJNzJnCmNQTjdyWFRFYVdDZUZlU3RYRzEz
            Z0ZMbmRpc1FjZFgwaUxhL2lzVzk0OGMKLS0tIHhKcVdJREtKc3p3eFdlMUMyR241
            Q0FiTWFXZGRwT3pqNUttQndnTzlLaHMKaa7YW9tcfqCFPdVJ6OxJ/afQfAhnss/4
            Qds08BCYM/JA7Cfkyksaba+wnx12QZww30ou3BycAQrWeHzFsdgPjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T04:45:26Z"
    mac: ENC[AES256_GCM,data:GnwxIiEyfQ0mgRJP2ATV/ZpTXitcB4vPJY7aZo660PmwfDF7rM1a4eeXSnGjjb6Har3MW3uiH97iifYXu319g6B4l2u34kbSz8UpKV5a+1t37kVDyMYGu17NRhkKmyqAcyCYCxtMgavk7BlXla0qhZynvL0Vb7zUYiUdgjMtVl8=,iv:ndWFweZ1BFkUUvwSJ8hM2eBSfVjUOIXs0p5MAIwrXr4=,tag:qdP223ykVL27llBeG1r4eQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
