---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: iot
spec:
  releaseName: esphome
  interval: 10m
  chart:
    spec:
      chart: esphome
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: esphome/esphome
      tag: 2022.6.2
    env:
      ESPHOME_DASHBOARD_USE_PING: true
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
          hajimari.io/enable: "true"
          hajimari.io/icon: chip
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: 'esphome.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'esphome.${SECRET_DOMAIN}'
            secretName: esphome-tls
    persistence:
      config:
        enabled: true
        existingClaim: esphome-config
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 1
        memory: 1Gi
