---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-v2
  namespace: highseas
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
