# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: family-secrets
    namespace: family
stringData:
    SECRET_FAMILY_ROOT_PASS: ENC[AES256_GCM,data:sGgChlq74ynryseM6GO2gsE4Sk9ESmg+/ChA2wak5qo=,iv:UvX9HU3EC/zAQeK2vcLCVU51RkghxxQEIedd+y3gIlE=,tag:vkMQkw83CieyGa3ZRJX1uw==,type:str]
    SECRET_FAMILY_PGADMIN_EMAIL: ENC[AES256_GCM,data:a37WgTfbAK8HUI8dm0m3Bw==,iv:o2sCdmhVjdR4iSSqmT6gmZh3JsyuCihnE0XiZmmA4EE=,tag:dEIOUfDG5Op5kCYCRwWKBA==,type:str]
    SECRET_FAMILY_PGADMIN_PASS: ENC[AES256_GCM,data:BvV2RR+1gTNIzXgYzSQyA9bYyvM=,iv:xN8fsewmTeOKlPPe3KWbWFfgNXauKsouA7lVpslXvw4=,tag:FVq8g5uFZ82io1f3PI636A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fx3dv6dtxmjfd78qhnha9klxwwqsrqyjm2vphu062dzqrrdf7dgq7862s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOFgvc29YbnExL0c4b09M
            YVZpNzVPNGN1VFhuSWdRTnVzdEZDVUdSK1ZVCjNtSDZWSWRzOEhNK1VFTld6NWN0
            UUkxYzczRWdGZUVoNUZWKzUyakY0YWMKLS0tIFppb3lhbzlBQjlQQ1Z4aERZcE9H
            NUlYd2t3ZjBpQ3VZdmdRdEVoVXhFdHMKnReheGBf2NxHBe/CX666zK0I2zwt8Uo2
            2x1r5V7pyMQgdDspOZbkJzCOBKaFgNpZNw15fJDSZ5/pFeELZiiBuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-13T19:10:20Z"
    mac: ENC[AES256_GCM,data:lz7eHzVL+C3jJsr+7CQmDouqTepWCQO5B/iYw00Li8L3P19znnaGhiCMTBuapw8+91sQWbDeAGJx0CODm+Im55lgEst1zwmd0lye+aPDz5b0UURjlD0zkmwu8ek7e+HwRhiwHbeSp9X73vHjMAhFu7Nbdzf/nem72jPeAHEDI74=,iv:jLqbYpKFTrchVa0X6qmWi0Jf5xyKMlvwDSxGCZsh7UI=,tag:o7DYsABKNyWi4dU+b2rANg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
