---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage-longhorn
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      # backupTarget: s3://longhorn@minio/backups
      # backupTargetCredentialSecret: longhorn-backup
      defaultDataPath: /mnt/disk0/longhorn
      defaultReplicaCount: 2
      defaultLonghornStaticStorageClass: longhorn
    ingress:
      enabled: true
      ingressClassName: "nginx"
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      tlsSecret: "longhorn-tls"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "content-save"
        hajimari.io/appName: "longhorn"
        nginx.ingress.kubernetes.io/whitelist-source-range: "${SECRET_NETWORK_INGRESS_WHITELIST}"
