---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr
  namespace: lowseas
spec:
  maxHistory: 3
  interval: 5m
  suspend: false
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: haveagitgat/tdarr
      tag: 2.00.18
      pullPolicy: IfNotPresent
    env:
      TZ: ${TZ}
      serverIP: 0.0.0.0
      ffmpegPath: /usr/bin/ffmpeg
    persistence:
      config:
        enabled: true
        mountPath: /app/configs
        existingClaim: tdarr-config
      data:
        enabled: true
        mountPath: /app/server
        existingClaim: tdarr-data
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
      media:
        enabled: true
        type: nfs
        server: "${SECRET_NFS_SERVER_IP}"
        path: "${SECRET_NFS_SERVER_MEDIA_PATH}"
        mountPath: /media
    service:
      main:
        ports:
          http:
            port: 8265
          server:
            enabled: true
            protocol: TCP
            port: 8266
    ingress:
      main:
        enabled: true
        ingressClassName: 'nginx'
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: alpha-t-circle
          nginx.ingress.kubernetes.io/whitelist-source-range: "${SECRET_NETWORK_INGRESS_WHITELIST}"
        hosts:
          - host: 'tdarr.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'tdarr.${SECRET_DOMAIN}'
            secretName: tdarr-tls
    resources: {}
