---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: iot
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 13.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.7.7
    env:
      TZ: "${TIMEZONE}"
    # envFrom:
    #   - secretRef:
    #       name: home-assistant
    # hostNetwork: true
    # dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        # externalIPs:
        #   - "${SVC_HOME_ASSISTANT_ADDR}"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: hass-config
    mariadb:
      enabled: true
      auth:
        password: ${SECRET_HASS_DB_PASS}
        rootPassword: ${SECRET_HASS_DB_PASS}
      primary:
        persistence:
          enabled: true
          storageClass: "longhorn"
    podAnnotations:
      secret.reloader.stakater.com/reload: "home-assistant"
    addons:
      codeserver:
        enabled: true
        image:
          repository: docker.io/codercom/code-server
          tag: 4.5.1
        env:
          TZ: "${TIMEZONE}"
        # git:
        #   deployKeySecret: code-server
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            hajimari.io/enable: "false"
            hajimari.io/icon: "code-braces-box"
            nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
          hosts:
            - host: "hass-config.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - hass-config.${SECRET_DOMAIN}
              secretName: "hass-config-tls"
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi
