---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: psql-family
  namespace: family
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.6.24
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    auth:
      postgresPassword: "${SECRET_PSQL_FAMILY_ROOT_PASS}"
    primary:
      persistence:
        enabled: true
        existingClaim: psql-family-data
