---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres10-config
  namespace: dbs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
