---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres10
  namespace: dbs
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 11.8.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  # values yaml: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
  values:
    global:
      postgresql:
        auth:
          existingSecret: postgres10-secrets
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 10-debian-11
      pullPolicy: IfNotPresent

    auth:
      database: ${SECRET_DBS_POSTGRES10_DB_NAME}

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

      resources:
        requests:
          cpu: 11m
          memory: 32M
        limits:
          cpu: 11m
          memory: 32M

    primary:
      persistence:
        enabled: true
        existingClaim: postgres10-config

      service:
        type: LoadBalancer
        loadBalancerIP: ${SECRET_DBS_POSTGRES10_ADDRESS}

      resources:
        requests:
          cpu: 22m
          memory: 256M
        limits:
          memory: 3072M
