---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config-v2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
