---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: food-config
  namespace: family
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
