---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recipes
  namespace: family
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: recipes
      version: 6.6.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true

  values:
    image:
      repository: vabene1111/recipes
      tag: 1.3.3
      pullPolicy: IfNotPresent

    env:
      DEBUG: 1
      EMAIL_HOST: "${SECRET_FOOD_EMAIL_HOST}"
      EMAIL_PORT: 587
      EMAIL_HOST_PASSWORD: "${SECRET_FOOD_EMAIL_KEY}"
      EMAIL_HOST_USER: "${SECRET_FOOD_EMAIL_USER}"
      EMAIL_USE_TLS: 1
      EMAIL_USE_SSL: 0
      DEFAULT_FROM_EMAIL: "${SECRET_FOOD_EMAIL_ADDR}"
      ACCOUNT_EMAIL_SUBJECT_PREFIX: "[Recipes]"
      TIMEZONE: ${TIMEZONE}
      SECRET_KEY: ${SECRET_FOOD_SECRET_KEY}

    sidecar:
      image:
        repository: nginx
        tag: 1.23.1
        pullPolicy: IfNotPresent

    persistence:
      config:
        enabled: true
        existingClaim: food-config
      database:
        enabled: true
        existingClaim: food-database
        mountPath: /opt/recipes/db.sqlite3
        subPath: db.sqlite3
      media:
        enabled: true
        existingClaim: food-media
        mountPath: /opt/recipes/mediafiles
      static:
        enabled: true
        type: emptyDir
        mountPath: /opt/recipes/staticfiles

    service:
      main:
        annotations:
          prometheus.io/probe: "true"
          prometheus.io/protocol: http

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'food'
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: "food.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "food.${SECRET_DOMAIN}"
            secretName: "food-tls"
